
status_update_frequency: 60
database_host: "localhost"
database_port: 3306
database_name: "network_link"
database_user: "nuuser"
database_pass: "nupass!"
discord_enabled: true
discord_server_id: "597852732472426506"
discord_tracked_tracks:
  - "default"
discord_token_size: 4
discord_token_lifespan: 120
discord_channel_id: "538879606527098900"
discord_status_channel_id: "701115144842903615"
discord_command_character: "!"
discord_network_bot_token: "REDACTED"
discord_network_bot_playing_message: "on the ORE Network"
greeting_message: "%USER% joined the network."
farewell_message: "%USER% left the network."
enable_special_quirky_message: false
quirky_message_frequency: 1000
quirky_greeting_message: "Running %USER%.exe ..."
quirky_farewell_message: "%USER%.exe has stopped working."
enable_special_farewells_and_greetings: false
discord_ignore_ids:
  - "550377585192730634"
  - "550377656428920852"
  - "550377705389162496"
  - "550377749366177792"
  - "550378049183416341"
  - "550378104846286849"
  - "550378142662131712"
  - "552245840052486164"
  - "538878359401267202"
message_farewells:
  - "Come back soon!"
  - "We hope to see you soon!"
  - "Cya!"
  - "Don't forget to like and subscribe!"
message_greetings:
  - "glhf!"
  - "Everyone, look busy!"
  - "We were expecting you ( ͡° ͜ʖ ͡°)"
  - "We hope you brought pizza."
  - "Leave your weapons by the door."
  - "Hide the bananas!"
  - "Unleash the corr!"
  - "Quick, ask Digitalis about linked lists!"
  - "Ask for nicktatorship while you're at it!"